package com.github.frtu.samples.dataprocessing.transform

import com.github.frtu.dataprocessing.framework.Step
import com.github.frtu.dataprocessing.framework.Transformer
import com.github.frtu.dataprocessing.framework.TransformContext
import com.github.frtu.dataprocessing.framework.utils.TypedJsonDeserializerFunction
import com.github.frtu.samples.dataprocessing.model.input.Email
import com.github.frtu.samples.dataprocessing.model.input.EmailDetail
import com.github.frtu.samples.dataprocessing.model.output.EmailEntity
import com.github.frtu.samples.dataprocessing.model.output.STATUS
import com.github.frtu.samples.dataprocessing.transform.EmailTransformer.Companion.FINAL_TRANSFORM_STEP_NAME
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId

@Step(FINAL_TRANSFORM_STEP_NAME)
class EmailTransformer(
    private val typedJsonDeserializerFunction: TypedJsonDeserializerFunction<EmailDetail>
) : Transformer<Email, EmailEntity> {
    override fun process(input: Email, ctx: TransformContext): EmailEntity? {
        val emailDetail = typedJsonDeserializerFunction.convert(input.content)
        return EmailEntity(
            receiver = null, // Will be set later in processing pipeline
            subject = emailDetail.subject!!,
            content = input.content,
            status = STATUS.INIT,
            id = null, // Will be generated by persistence layer
            creationTime = convertToLocalDateTime(input.createdTimeMillis),
            updateTime = convertToLocalDateTime(input.updatedTimeMillis)
        )
    }

    private fun convertToLocalDateTime(epochMillis: Long): LocalDateTime {
        return LocalDateTime.ofInstant(Instant.ofEpochMilli(epochMillis), ZoneId.systemDefault())
    }

    companion object {
        const val FINAL_TRANSFORM_STEP_NAME = "final"
    }
}
