package com.github.frtu.samples.dataprocessing.transform

import com.github.frtu.dataprocessing.framework.Transform
import com.github.frtu.dataprocessing.framework.TransformContext
import com.github.frtu.samples.dataprocessing.model.input.Email
import com.github.frtu.samples.dataprocessing.model.output.EmailEntity
import com.github.frtu.samples.dataprocessing.model.output.STATUS
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId

class EmailTransform : Transform<Email, EmailEntity> {
    override fun process(input: Email, ctx: TransformContext): EmailEntity? {
        return EmailEntity(
            receiver = null, // Will be set later in processing pipeline
            subject = input.subject,
            content = input.content,
            status = STATUS.INIT,
            id = null, // Will be generated by persistence layer
            creationTime = convertToLocalDateTime(input.createdTimeMillis),
            updateTime = convertToLocalDateTime(input.updatedTimeMillis)
        )
    }

    private fun convertToLocalDateTime(epochMillis: Long): LocalDateTime {
        return LocalDateTime.ofInstant(Instant.ofEpochMilli(epochMillis), ZoneId.systemDefault())
    }
}
